---
title: "ESTP-course in BI with Power BI"
description: |
  Information about the ESTP-webinar on Power BI held on the 22.-24. april 2021.  
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction

This course/webinar is intended for newcomers to Power BI, who want to learn more about how to use
a business intelligence tool like Power BI to visualize data. The course is also geared towards the 
type of data ususally seen in the production of official staistics.  


# 1. Installation

The only prerequisite for attending the course is that you Power BI Desktop installed on a computer that 
is at your disposal during the 3-day course. We will only use the Desktop-software, which is free, so there
is no need to install anything more. PLease download the latest version.

## 1.2 Settings

We recommend to choose the following settings in Power BI desktop: 

- Set english as the language. 
- 

# 2. Getting started

## 2.1 Videos

This video gives you a nice introduction to what Power BI is:

<iframe width="560" height="315" src="https://www.youtube.com/embed/Vqz2d7pTOV8" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


