---
title: "Itinerary"
description: |
  Detailed plan for the 3-day-course
output: 
  distill::distill_article:
    toc: true
    toc_debth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# **DAY 1**


| What                                                                      | Who         | Time          |
| ------------------------------------------------------------------------- | ----------- | ------------- |
| Introduction to the course                                                | Øyvind      | 09.00 - 09.30 |
| Fundamentals of Power BI                                                  | Carl        | 09.30 - 10.00 |
| Break                                                                     |             | 10.00 - 10.15 |
| Task: Importing data and creating a visual                                | Øyvind/Carl | 10.15 - 10.30 |
| Building a data model                                                     | Øyvind      | 10.30 - 11.00 |
| Break                                                                     |             | 11.00 - 11.15 |
| Task: Importing more data and building a data model                       | Øyvind/Carl | 11.15 - 11.30 |
| Cleaning data in Power Query                                              | Øyvind      | 11.30 - 12.00 |
| Lunch                                                                     |             | 12.00 - 12.30 |
| Task: Find the errors in the data and fix them                            |             | 12.30 - 12.45 |
| Measures: the optimal way to do calculations                              | Øyvind      | 12.45 - 13.15 |
| Break                                                                     |             | 13.15 - 13.30 |
| Task: Create your own measures and visualize them                         |             | 13.30 - 13.45 |
| Beautify your report                                                      | Øyvind      | 13.45 - 14.15 |
| Break                                                                     |             | 14.15 - 14.30 |
| Task: Change the background and colors of your dashboard                  |             | 14.30 - 14.45 |
| Filter context and drilldown                                              | Øyvind      | 14.45 - 15.15 |
| Task: Change the context of different visuals and create a drilldown page |             | 15.15 - 15.45 |
| Walking through the assigment for day 2                                   | Øyvind      | 15.45 - 16.15 |


# **DAY 2**

Participants work on their own project. 

# **DAY 3**

| What                                                    | Who    | Time          |
| ------------------------------------------------------- | ------ | ------------- |
| Show and tell: participants share their projects        |        | 09.00 - 09.30 |
| Modern visualization: the importance of the web browser | Carl   | 09.30 - 10.00 |
| Import data from Eurostat API                           | Carl   | 10.00 - 10.15 |
| Break                                                   |        | 10.15 - 10.30 |
| Task: Import data from EUROSTAT                         |        | 10.30 - 10.45 |
| Import classifications                                  | Carl   | 10.45 - 11.00 |
| Task: Import classifications                            |        | 11.00 - 11.15 |
| Break                                                   |        | 11.15 - 11.30 |
| Using R and Python in Power BI                          | Øyvind | 11.30 - 12.00 |
